# -*- coding:utf-8 -*-

d = (
    ('00','OTROS'),
    ('01','FACTURA'),
    ('02','RECIBO DE HONORARIOS'),
    ('03','BOLETA DE VENTA'),
    ('04','LIQUIDACION DE COMPRA'),
    ('05','BOLETO DE AVIACION'),
    ('06','CARTA DE PODER AEREO'),
    ('07','NOTA DE CREDITO'),
    ('08','NOTA DE DEVITO'),
    ('09','GUIA DE REMICION'),
    ('10','RECIBO DE ARRENTAMIENTO'),
    ('11','POLIZA BOLSA DE VALORES'),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
    ('',''),
)
