# -*- coding:utf-8 -*-

q =(
    ('001','OPERACIONES CON IGV'),
    ('002','HONORARIOS'),
    ('004','OPERACIONES REPARABLES'),
    ('123','CANJE DE LETRAS'),
    ('411','REMUNERACION EMPLEADOS'),
    ('412','REMUNERACION OBREROS'),
    ('413','CONSTRUCCION CIVIL'),
    ('910','COSTOS DE PRODUCCION'),
    ('940','COSTOS DE ADMINISTRACION'),
    ('950','COSTOS DE ADMINISTRACION'),
)
#print q
